<?php

/**
 * @file
 * Provides hook implementations for the Search API AI Chatbot module.
 */

 /**
  * Implements hook_theme().
  */
function search_api_ai_chatbot_theme() {
  return [
    'search_api_ai_chatbot' => [
      'variables' => [
        'header' => '',
        'rendered_form' => '',
        'messages' => [],
      ]
    ],
    'search_api_ai_chatbot_message' => [
      'variables' => [
        'message' => [],
        'username' => 'Chatbot',
        'timestamp' => '',
      ],
    ],
  ];
}


/**
 * Implements preprocess function for search_api_ai_chatbot_message theme.
 */
function template_preprocess_search_api_ai_chatbot_message(&$variables) {

}
