ckeditor5.plugin.ai_ckeditor_ai:
  type: mapping
  label: AI CKEditor configuration
  mapping:
    plugins:
      type: sequence
      label: 'Plugins'
      orderby: key
      sequence:
        type: ckeditor5.plugin.ai_ckeditor_ai.[%key]
