ckeditor5.plugin.ai_ckeditor_ai:
  type: mapping
  label: AI CKEditor configuration
  mapping:
    completion:
      type: mapping
      label: Completion configuration
      mapping:
        enabled:
          type: boolean
          label: 'Enabled'
        provider:
          type: string
          label: 'Provider'
