ai_automators.ai_automator.*:
  type: config_entity
  label: AI Automator
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    entity_type:
      type: string
      label: Entity Type
    bundle:
      type: string
      label: Bundle
    field_name:
      type: string
      label: Field Name
    worker_type:
      type: string
      label: Worker Type
    weight:
      type: weight
      label: Weight
    automator_types:
      type: sequence
      sequence:
        type: mapping
        mapping:
          uuid:
            type: uuid
          id:
            type: string
            constraints:
              PluginExists:
                manager: plugin.manager.ai_automator
                interface: 'Drupal\ai_automators\PluginInterfaces\AiAutomatorTypeInterface'
          label:
            type: string
            label: 'Custom Label'
          weight:
            type: weight
          settings:
            type: sequence
            label: Plugin Config
            sequence:
              type: ignore

# @todo add schema for types.
ai_automators.automator_type.*:
  type: mapping
  label: 'automator type settings'

ai_automators.automators_tool.*:
  type: config_entity
  label: Automators Tool
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

ai_automators.automator_chain_type.*:
  type: config_entity
  label: 'Automator Chain type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
