<?php

/**
 * @file
 * Update the Search API module.
 */

/**
 * Implements hook_update_N().
 */
function search_api_ai_update_10301() {
  // Enable the submodule search_api_ai_simple_chatbot.
  \Drupal::service('module_installer')->install(['search_api_ai_simple_chatbot']);
  // Send a message to the user, that the submodule was enabled and can be
  // removed if not needed.
  \Drupal::messenger()->addMessage(t('As part of the update, we have split up
  the Simple Chatbot block and the core module, but have gone ahead and
  installed the submodule for backwards compability. If you are not using the
  Simple Chatbot block, you may uninstall it.'));
}
