<?php

/**
 * @file
 * AI Search install file.
 */

/**
 * Update the servers that use AI Search with nested database settings.
 */
function ai_search_update_10001() {
  $config_factory = \Drupal::configFactory();
  $servers = $config_factory->listAll('search_api.server.');
  if (empty($servers)) {
    return t('No Search API servers found to review for changes.');
  }

  $updated_servers = 0;
  foreach ($servers as $server) {
    $config_object = $config_factory->getEditable($server);
    $config = $config_object->getRawData();

    // It must be an AI Search server.
    if (
      empty($config['dependencies']['module'])
      || !in_array('ai_search', $config['dependencies']['module'])
    ) {
      continue;
    }

    // Nest the database settings that were previous higher level settings
    // within the server back-end configuration.
    if (!isset($config['backend_config']['database_settings'])) {
      $config['backend_config']['database_settings'] = [
        'database_name' => $config['backend_config']['database_name'],
        'collection' => $config['backend_config']['collection'],
        'metric' => $config['backend_config']['metric'],
      ];
      unset($config['backend_config']['database_name']);
      unset($config['backend_config']['collection']);
      unset($config['backend_config']['metric']);
      $config_object->set('backend_config', $config['backend_config']);
      $config_object->save();
      $updated_servers++;
    }
  }

  return t('Search API Servers using the AI Search module updated database settings: @number.', [
    '@number' => $updated_servers,
  ]);
}
